### ISSUE TITLE
Error with MagneticWishbone 1.1.0 after resent game update 219.14

### ISSUE THREAD

**Issue by Gyrofalcon** [Terrenteller/Valheim-Plugins#6]
> [Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type ObjectDB and name UpdateItemHashes and parameters
> [Error  : Unity Log] ArgumentException: Undefined target method for patch method static void MagneticWishbone.MagneticWishbone+ObjectDBPatch::UpdateItemHashesPostfix()
> Stack trace:
> HarmonyLib.PatchClassProcessor.PatchWithAttributes (System.Reflection.MethodBase& lastOriginal) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> Rethrow as HarmonyException: Patching exception in method null
> HarmonyLib.PatchClassProcessor.ReportException (System.Exception exception, System.Reflection.MethodBase original) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.PatchClassProcessor.Patch () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.<PatchAll>b__11_0 (System.Type type) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.CollectionExtensions.Do[T] (System.Collections.Generic.IEnumerable`1[T] sequence, System.Action`1[T] action) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.PatchAll (System.Reflection.Assembly assembly) (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> HarmonyLib.Harmony.PatchAll () (at <474744d65d8e460fa08cd5fd82b5d65f>:0)
> MagneticWishbone.MagneticWishbone.Awake () (at <9e0a96295ae34f24b3874edb9544a699>:0)
> UnityEngine.GameObject:AddComponent(Type)
> BepInEx.Bootstrap.Chainloader:Start()
> UnityEngine.GameObject:.cctor()
> PlatformTools.Common.SingletonMonoBehaviour`1:get_Instance()
> PlatformTools.PlatformManagerInitializer:OnRuntimeMethodLoad()

Not tested what works or not in game. Have no history with this mod, since I was using MagnetMod until this update.
Jotunn v 2.21.3, BepinEx 5.4.2202

**Comment by Terrenteller** [comment]
Fixed in 3d21736cf4b820f972bd774647b405318c3b8007. Thank you for the report.
